/****************************************************************************
**
** Metadata for OmniRig generated by dumpcpp v6.10.1 using
** C:\msys64\mingw64\bin\dumpcpp.exe -o C:/Users/IU8LMC/Downloads/WSJTX_3.0_Source/build-w2/OmniRig C:/Program Files (x86)/Afreet/OmniRig/OmniRig.exe
** from the type library C:\Program Files (x86)\Afreet\OmniRig\OmniRig.exe
**
****************************************************************************/

#define QAX_DUMPCPP_OMNIRIG_NOINLINES
#include "C:/Users/IU8LMC/Downloads/WSJTX_3.0_Source/build-w2/OmniRig.h"
#include <OAIdl.h>

